version: '3.8'
services:
  postgres-products:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: products_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - products_data:/var/lib/postgresql/data

  postgres-orders:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: orders_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5433:5432"
    volumes:
      - orders_data:/var/lib/postgresql/data

volumes:
  products_data:
  orders_data:
